apiVersion: apps/v1
kind: Deployment
metadata:
  name: pythondemoapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pythondemoapp
  template:
    metadata:
      labels:
        app: pythondemoapp
    spec:
      containers:
      - name: pythondemoapp
        image: asia-south1-docker.pkg.dev/haritha-project1/haritha-cicd-demo-dev-repo/pythondemoimage:${imageTag}
        ports:
        - containerPort: 9090